spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: CustomerService
        uri: http://localhost:8081
        predicates:
        - Path=/customers/**
      - id: BookCommandService
        uri: http://localhost:8082
        predicates:
        - Path=/books/**
      - id: BookQueriesService
        uri: http://localhost:8083
        predicates:
          - Path=/bookQ/**
      - id: BorrowingService
        uri: http://localhost:8084
        predicates:
          - Path=/borrowings/**
      - id: ReviewService
        uri: http://localhost:8085
        predicates:
          - Path=/reviews/**

            
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ , http://localhost:8762/eureka/


