server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: libraryDB
  cloud:
    config:
      import-check:
        enabled: true
  kafka:
    consumer:
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    app:
      topic:
        tofasttopic: senderC

  application:
    name: BookCommandService

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

